<?php
global $_GPC, $_W;
$weid = $this->_weid;
$action = 'queueorder';
$title = $this->actions_titles[$action];

$storeid = intval($_GPC['storeid']);
//检查门店
$this->checkStore($storeid);
$title = $this->actions_titles[$action];
$returnid = $this->checkPermission($storeid);
//当前门店
$cur_store = $this->getStoreById($storeid);
//设置菜单
$GLOBALS['frames'] = $this->getNaveMenu($storeid,$action);
if($_POST){
    // var_dump($_POST );
    $arr = unserialize(file_get_contents('language_en.txt'));
    $arr[en_name] =trim($_POST['en_name']);
    $arr[en_tel] =trim($_POST['en_tel']);
    $arr[en_code] =trim($_POST['en_code']);
    $arr[en_area] =trim($_POST['en_area']);
    $arr[en_address] =trim($_POST['en_address']);
    $arr[en_people] =trim($_POST['en_people']);
    $arr[en_smoke] =trim($_POST['en_smoke']);
    $arr[en_time] =trim($_POST['en_time']);
    $arr[en_table] =trim($_POST['en_table']);
    $arr[en_remark] =trim($_POST['en_remark']);
    $arr[en_num] =trim($_POST['en_num']);
    $arr[en_free] =trim($_POST['en_free']);
    $arr[en_count] =trim($_POST['en_count']);
    $arr[en_trueorder] =trim($_POST['en_trueorder']);
    $arr[en_true] =trim($_POST['en_true']);
    $arr[en_sale] =trim($_POST['en_sale']);
    $arr[en_orderh] =trim($_POST['en_orderh']);
    $arr[en_orders] =trim($_POST['en_orders']);
    $arr[en_p] =trim($_POST['en_p']);
    $arr[en_index] =trim($_POST['en_index']);
    $arr[en_true1] =trim($_POST['en_true1']);
    $arr[en_true2] =trim($_POST['en_true2']);
    $arr[en_true3] =trim($_POST['en_true3']);
    $arr[en_yuyue] =trim($_POST['en_yuyue']);
    $arr[en_issmoke] =trim($_POST['en_issmoke']);
    $arr[en_nosmoke] =trim($_POST['en_nosmoke']);
    $arr[en_more] =trim($_POST['en_more']);
    file_put_contents('language_en.txt',serialize($arr));

    //日文
    $jparr = unserialize(file_get_contents('language_jp.txt'));
    $jparr[jp_name] =trim($_POST['jp_name']);
    $jparr[jp_tel] =trim($_POST['jp_tel']);
    $jparr[jp_code] =trim($_POST['jp_code']);
    $jparr[jp_area] =trim($_POST['jp_area']);
    $jparr[jp_address] =trim($_POST['jp_address']);
    $jparr[jp_people] =trim($_POST['jp_people']);
    $jparr[jp_smoke] =trim($_POST['jp_smoke']);
    $jparr[jp_time] =trim($_POST['jp_time']);
    $jparr[jp_table] =trim($_POST['jp_table']);
    $jparr[jp_remark] =trim($_POST['jp_remark']);
    $jparr[jp_num] =trim($_POST['jp_num']);
    $jparr[jp_free] =trim($_POST['jp_free']);
    $jparr[jp_count] =trim($_POST['jp_count']);
    $jparr[jp_trueorder] =trim($_POST['jp_trueorder']);
    $jparr[jp_true] =trim($_POST['jp_true']);
    $jparr[jp_sale] =trim($_POST['jp_sale']);
    $jparr[jp_orderh] =trim($_POST['jp_orderh']);
    $jparr[jp_orders] =trim($_POST['jp_orders']);
    $jparr[jp_p] =trim($_POST['jp_p']);
    $jparr[jp_index] =trim($_POST['jp_index']);
    $jparr[jp_true1] =trim($_POST['jp_true1']);
    $jparr[jp_true2] =trim($_POST['jp_true2']);
    $jparr[jp_true3] =trim($_POST['jp_true3']);
    $jparr[jp_yuyue] =trim($_POST['jp_yuyue']);
    $jparr[jp_issmoke] =trim($_POST['jp_issmoke']);
    $jparr[jp_nosmoke] =trim($_POST['jp_nosmoke']);
    $jparr[jp_more] =trim($_POST['jp_more']);
    file_put_contents('language_jp.txt',serialize($jparr));

      //韩文
    $hwarr = unserialize(file_get_contents('language_hw.txt'));
    $hwarr[hw_name] =trim($_POST['hw_name']);
    $hwarr[hw_tel] =trim($_POST['hw_tel']);
    $hwarr[hw_code] =trim($_POST['hw_code']);
    $hwarr[hw_area] =trim($_POST['hw_area']);
    $hwarr[hw_address] =trim($_POST['hw_address']);
    $hwarr[hw_people] =trim($_POST['hw_people']);
    $hwarr[hw_smoke] =trim($_POST['hw_smoke']);
    $hwarr[hw_time] =trim($_POST['hw_time']);
    $hwarr[hw_table] =trim($_POST['hw_table']);
    $hwarr[hw_remark] =trim($_POST['hw_remark']);
    $hwarr[hw_num] =trim($_POST['hw_num']);
    $hwarr[hw_free] =trim($_POST['hw_free']);
    $hwarr[hw_count] =trim($_POST['hw_count']);
    $hwarr[hw_trueorder] =trim($_POST['hw_trueorder']);
    $hwarr[hw_true] =trim($_POST['hw_true']);
    $hwarr[hw_sale] =trim($_POST['hw_sale']);
    $hwarr[hw_orderh] =trim($_POST['hw_orderh']);
    $hwarr[hw_orders] =trim($_POST['hw_orders']);
    $hwarr[hw_p] =trim($_POST['hw_p']);
    $hwarr[hw_index] =trim($_POST['hw_index']);
    $hwarr[hw_true1] =trim($_POST['hw_true1']);
    $hwarr[hw_true2] =trim($_POST['hw_true2']);
    $hwarr[hw_true3] =trim($_POST['hw_true3']);
    $hwarr[hw_yuyue] =trim($_POST['hw_yuyue']);
    $hwarr[hw_issmoke] =trim($_POST['hw_issmoke']);
    $hwarr[hw_nosmoke] =trim($_POST['hw_nosmoke']);
    $hwarr[hw_more] =trim($_POST['hw_more']);
    file_put_contents('language_hw.txt',serialize($hwarr));

      //py
    $pyarr = unserialize(file_get_contents('language_py.txt'));
    $pyarr[py_name] =trim($_POST['py_name']);
    $pyarr[py_tel] =trim($_POST['py_tel']);
    $pyarr[py_code] =trim($_POST['py_code']);
    $pyarr[py_area] =trim($_POST['py_area']);
    $pyarr[py_address] =trim($_POST['py_address']);
    $pyarr[py_people] =trim($_POST['py_people']);
    $pyarr[py_smoke] =trim($_POST['py_smoke']);
    $pyarr[py_time] =trim($_POST['py_time']);
    $pyarr[py_table] =trim($_POST['py_table']);
    $pyarr[py_remark] =trim($_POST['py_remark']);
    $pyarr[py_num] =trim($_POST['py_num']);
    $pyarr[py_free] =trim($_POST['py_free']);
    $pyarr[py_count] =trim($_POST['py_count']);
    $pyarr[py_trueorder] =trim($_POST['py_trueorder']);
    $pyarr[py_true] =trim($_POST['py_true']);
    $pyarr[py_sale] =trim($_POST['py_sale']);
    $pyarr[py_orderh] =trim($_POST['py_orderh']);
    $pyarr[py_orders] =trim($_POST['py_orders']);
    $pyarr[py_p] =trim($_POST['py_p']);
    $pyarr[py_index] =trim($_POST['py_index']);
    $pyarr[py_true1] =trim($_POST['py_true1']);
    $pyarr[py_true2] =trim($_POST['py_true2']);
    $pyarr[py_true3] =trim($_POST['py_true3']);
    $pyarr[py_yuyue] =trim($_POST['py_yuyue']);
    $pyarr[py_issmoke] =trim($_POST['py_issmoke']);
    $pyarr[py_nosmoke] =trim($_POST['py_nosmoke']);
    $pyarr[py_more] =trim($_POST['py_more']);
    file_put_contents('language_py.txt',serialize($pyarr));

     //繁体
    $ftarr = unserialize(file_get_contents('language_ft.txt'));
    $ftarr[ft_name] =trim($_POST['ft_name']);
    $ftarr[ft_tel] =trim($_POST['ft_tel']);
    $ftarr[ft_code] =trim($_POST['ft_code']);
    $ftarr[ft_area] =trim($_POST['ft_area']);
    $ftarr[ft_address] =trim($_POST['ft_address']);
    $ftarr[ft_people] =trim($_POST['ft_people']);
    $ftarr[ft_smoke] =trim($_POST['ft_smoke']);
    $ftarr[ft_time] =trim($_POST['ft_time']);
    $ftarr[ft_table] =trim($_POST['ft_table']);
    $ftarr[ft_remark] =trim($_POST['ft_remark']);
    $ftarr[ft_num] =trim($_POST['ft_num']);
    $ftarr[ft_free] =trim($_POST['ft_free']);
    $ftarr[ft_count] =trim($_POST['ft_count']);
    $ftarr[ft_trueorder] =trim($_POST['ft_trueorder']);
    $ftarr[ft_true] =trim($_POST['ft_true']);
    $ftarr[ft_sale] =trim($_POST['ft_sale']);
    $ftarr[ft_orderh] =trim($_POST['ft_orderh']);
    $ftarr[ft_orders] =trim($_POST['ft_orders']);
    $ftarr[ft_p] =trim($_POST['ft_p']);
    $ftarr[ft_index] =trim($_POST['ft_index']);
    $ftarr[ft_true1] =trim($_POST['ft_true1']);
    $ftarr[ft_true2] =trim($_POST['ft_true2']);
    $ftarr[ft_true3] =trim($_POST['ft_true3']);
    $ftarr[ft_yuyue] =trim($_POST['ft_yuyue']);
    $ftarr[ft_issmoke] =trim($_POST['ft_issmoke']);
    $ftarr[ft_nosmoke] =trim($_POST['ft_nosmoke']);
    $ftarr[ft_more] =trim($_POST['ft_more']);
    file_put_contents('language_ft.txt',serialize($ftarr));

     //简体
    $cnarr = unserialize(file_get_contents('language_cn.txt'));
    $cnarr[cn_name] =trim($_POST['cn_name']);
    $cnarr[cn_tel] =trim($_POST['cn_tel']);
    $cnarr[cn_code] =trim($_POST['cn_code']);
    $cnarr[cn_area] =trim($_POST['cn_area']);
    $cnarr[cn_address] =trim($_POST['cn_address']);
    $cnarr[cn_people] =trim($_POST['cn_people']);
    $cnarr[cn_smoke] =trim($_POST['cn_smoke']);
    $cnarr[cn_time] =trim($_POST['cn_time']);
    $cnarr[cn_table] =trim($_POST['cn_table']);
    $cnarr[cn_remark] =trim($_POST['cn_remark']);
    $cnarr[cn_num] =trim($_POST['cn_num']);
    $cnarr[cn_free] =trim($_POST['cn_free']);
    $cnarr[cn_count] =trim($_POST['cn_count']);
    $cnarr[cn_trueorder] =trim($_POST['cn_trueorder']);
    $cnarr[cn_true] =trim($_POST['cn_true']);
    $cnarr[cn_sale] =trim($_POST['cn_sale']);
    $cnarr[cn_orderh] =trim($_POST['cn_orderh']);
    $cnarr[cn_orders] =trim($_POST['cn_orders']);
    $cnarr[cn_p] =trim($_POST['cn_p']);
    $cnarr[cn_index] =trim($_POST['cn_index']);
    $cnarr[cn_true1] =trim($_POST['cn_true1']);
    $cnarr[cn_true2] =trim($_POST['cn_true2']);
    $cnarr[cn_true3] =trim($_POST['cn_true3']);
    $cnarr[cn_yuyue] =trim($_POST['cn_yuyue']);
    $cnarr[cn_issmoke] =trim($_POST['cn_issmoke']);
    $cnarr[cn_nosmoke] =trim($_POST['cn_nosmoke']);
    $cnarr[cn_more] =trim($_POST['cn_more']);
    file_put_contents('language_cn.txt',serialize($cnarr));
    // die;
}
include $this->template('web/language');